# Generated by Django 4.2.1 on 2023-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
